export const blogPosts = [
  {
    id: 1,
    title: "How to Ace Your Technical Interview: A Complete Guide",
    excerpt: "Learn the essential strategies and techniques to succeed in technical interviews at top tech companies.",
    content: "Technical interviews can be daunting, but with the right preparation, you can turn them into opportunities to showcase your skills...",
    author: "CSL Team",
    publishedAt: "2024-01-10",
    readTime: "8 min read",
    category: "Interview Prep",
    slug: "how-to-ace-technical-interview",
    image: "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2069&q=80",
  },
  {
    id: 2,
    title: "ICPC Training: From Beginner to Competitor",
    excerpt: "Discover our comprehensive approach to competitive programming and how we prepare students for ICPC.",
    content: "Competitive programming is not just about solving problems quickly; it's about developing algorithmic thinking...",
    author: "CSL Team",
    publishedAt: "2024-01-08",
    readTime: "12 min read",
    category: "Competitive Programming",
    slug: "icpc-training-guide",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
  },
  {
    id: 3,
    title: "System Design Interview: Building Scalable Solutions",
    excerpt: "Master the art of system design interviews with our step-by-step approach and real-world examples.",
    content: "System design interviews are becoming increasingly important as companies look for engineers who can architect...",
    author: "CSL Team",
    publishedAt: "2024-01-05",
    readTime: "15 min read",
    category: "System Design",
    slug: "system-design-interview-guide",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2015&q=80",
  },
  {
    id: 4,
    title: "Behavioral Interview Success: The STAR Method",
    excerpt: "Learn how to structure your responses using the STAR method and ace your behavioral interviews.",
    content: "Behavioral interviews are designed to assess how you've handled situations in the past...",
    author: "CSL Team",
    publishedAt: "2024-01-03",
    readTime: "6 min read",
    category: "Interview Prep",
    slug: "behavioral-interview-star-method",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
  },
  {
    id: 5,
    title: "Success Story: From CSL to Google",
    excerpt: "Read about Sarah's journey from joining CSL to landing her dream job at Google.",
    content: "Sarah joined CSL in her sophomore year, unsure about her career path and interview preparation...",
    author: "CSL Team",
    publishedAt: "2024-01-01",
    readTime: "10 min read",
    category: "Success Stories",
    slug: "success-story-google",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2071&q=80",
  },
  {
    id: 6,
    title: "Mock Interview Tips: What We've Learned",
    excerpt: "Insights from conducting hundreds of mock interviews and helping students succeed.",
    content: "After conducting hundreds of mock interviews with students, we've identified common patterns...",
    author: "CSL Team",
    publishedAt: "2023-12-28",
    readTime: "7 min read",
    category: "Interview Prep",
    slug: "mock-interview-tips",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
  },
]; 