name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: # allows you to run manually too

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set Git identity
        run: |
          git config user.name "Hassan Chowdhry"
          git config user.email "hassan.chowdhry@dal.ca"
      
      - name: Add upstream repo
        run: |
          git remote add upstream https://github.com/DalCSL/csl-website.git
          git fetch upstream
      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main || echo "No changes to merge"
      - name: Push changes to fork
        run: |
          git push origin main
